### ISSUE TITLE
HDFS backups

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#10]
Files in HDFS are currently not backed up outside the cluster - dump in Ceph? Push into ACIS backup rotation?

**Comment by mjcollin** [comment]
Perhaps a Ceph-izer job that copies new things from /guoda/data into a Ceph bucket and categorize the rest of things as scratch.

**Comment by mjcollin** [comment]
HDFS became full and needed to archive some things:

/guoda/data/idigbio-media-2017* 

Now exists on moose and on storage backups. Moose is now serving as an archive machine. Need to formalize data policies, see also https://github.com/acislab/pragma-cloud-spark

**Comment by jhpoelen** [comment]
@ialzuru @nrejack hey y'all!  To address out of space issue that causes #68 ,  can we move more of idigbio-2018* and idigbio-media-2018* into moose? This would free up 1600GB + 200GB ~ 2TB in HDFS.
