### ISSUE TITLE
provide some method to indicate how busy the cluster is

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#19]
@diatomsRcool is using effechecka and effechecka is using the guoda service (as in the spark/mesos cluster). Now, jobs are getting rejected because the cluster is at capacity (all 192 cpus allocated), but @diatomsRcool has no way to know or take action other than opening an issue like 
 https://github.com/jhpoelen/effechecka/issues/68 .

Suggest to create some api or perhaps monitor webpage to indicate how busy the cluster is and who is taking up resources.

**Comment by godfoder** [comment]
The major issue is that there is a single 144 CPU framework, we should 
avoid letting people submit jobs of that size.

- Alex

**Comment by godfoder** [comment]
@mjcollin  had started a very large job, which I killed off. There should be plenty of resources avaialble now.

**Comment by godfoder** [comment]
There is an API endpoint that I think i can write quick dashboard for at:

http://mesos03.acis.ufl.edu:5050/metrics/snapshot

I'll look into it.

**Comment by jhpoelen** [comment]
Cool! Can we make it accessible at hamsters.guoda.bio ... this would fit nicely into the documentation of effechecka/freshdata api at https://github.com/gimmefreshdata/freshdata/wiki/api .

**Comment by godfoder** [comment]
Just working on the spinning wheel gif now whose spin rate is dictated by a rate limited requestAnimationFrame loop based on the used:total CPU ration.

**Comment by jhammock** [comment]
Some of us can't tell if you're kidding.

**Comment by godfoder** [comment]
[Dashboard prototype](https://web.archive.org/web/19991128125537/http://www.geocities.com/Heartland/Bluffs/4157/hampdance.html)

**Comment by jhpoelen** [comment]
excellent! were you thinking 1 CPU = 1 hamster, dancing when allocated? Great for demoing ; )

**Comment by jhpoelen** [comment]
You can now see how busy the cluster is by running [./cluster-status.sh](https://github.com/bio-guoda/preston-scripts/blob/master/cluster-status.sh) after cloning the repo in a jupyter.idigbio.org terminal instance.
