### ISSUE TITLE
Gouda datasets unavailable in Jupyter Notebooks

### ISSUE THREAD

**Issue by kevinlove** [bio-guoda/guoda-services#3]
Not sure what's broken, but the gouda datasets are unavailable:

``` 
os.listdir("/gouda")
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-d961d88a1c83> in <module>()
----> 1 os.listdir("/gouda")

FileNotFoundError: [Errno 2] No such file or directory: '/gouda'
```

**Comment by mjcollin** [comment]
os.listdir() a Python method that is executed by the Python kernel running on the Jupyter server. It is only aware of file systems mounted on that server. The GUODA data sets are stored in an HDFS cluster that is accessible via HDFS libraries (ie it is not accessed through a file system mount point) and those HDFS tolls are available on both the Jupyter server and on the Mesos worker nodes. There is custom magic default path configuration for the Spark API file system manipulation methods (read.parquet(<filename>) etc.) to use HDFS libraries to connect to the HDFS cluster and use files from there. That is why the paths in the examples look like local file paths.

Documentation for this should be here: https://github.com/bio-guoda/guoda-services/wiki/Jupyter-Notebooks but it is really sitting in a Github gist @nickynicolson wrote and hasn't been moved in yet.

Do the documented paths in the wiki get you through your work today?

**Comment by kevinlove** [comment]
Thanks for the explanation, but I should have added that the first place I went to look for help was the wiki. My example is showing that the path documented in the wiki is not mounted/available. So to answer your question in a succinct way:

No, the documented paths in the wiki do not get me through my work today.
