### ISSUE TITLE
convert dwca to parquet using spark job

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#30]
similar to #18 , but with extra prerequisites. Note that the example below is specific for inaturalist dwca archives - for other archives, the occurrences file ```occurrences.csv``` might be named differently.

0. login to https://jupyter.idigbio.org and start a terminal
1. download darwin core archive (e.g. ```wget http://www.inaturalist.org/observations/gbif-observations-dwca.zip```)
2. list content of zip file ```unzip -l gbif-observations-dwca.zip```
3. print contents of meta.xml by executing ```unzip -p gbif-observations-dwca.zip meta.xml```
3. stream meta.xml from dwca into hdfs
```unzip -p gbif-observations-dwca.zip meta.xml | hdfs dfs -put - /tmp/dwca/newresource/meta.xml ```
3. stream occurrences from dwca into hdfs ```unzip -p gbif-observations-dwca.zip observations.csv | hdfs dfs -put - /tmp/dwca/newresource/observations.csv ```. Streaming is used to avoid exhausting local hard drive before copying to hdfs. In theory you could directly stream from remote location into hdfs if no space is available for saving .zip file locally.
4. confirm that both files made it by listing ```hdfs dfs -ls -h /tmp/dwca/inaturalist/```
5. run job: ```curl -X POST http://mesos07.acis.ufl.edu:7077/v1/submissions/create --header "Content-Type:application/json;charset=UTF-8" --data @dwca-job.json```  with ```dwca-job.json``` : 
```json
{                                                                                                                                  
      "action" : "CreateSubmissionRequest",                                                                                        
      "appArgs" : [ "hdfs:///tmp/dwca/inaturalist/meta.xml"],                              
      "appResource" : "https://s3-us-west-2.amazonaws.com/guoda/idigbio-spark/iDigBio-LD-assembly-1.5.8.jar",                      
      "clientSparkVersion" : "2.0.1",                                                                                              
      "environmentVariables" : {                                                                                                   
        "SPARK_ENV_LOADED" : "1",                                                                                                  
        "HADOOP_HOME" : "/usr/lib/hadoop",                                                                                         
        "HADOOP_PREFIX" : "/usr/lib/hadoop",                                                                                       
        "HADOOP_LIBEXEC_DIR" : "/usr/lib/hadoop/libexec",                                                                          
        "HADOOP_CONF_DIR" : "/etc/hadoop/conf",                                                                                    
        "HADOOP_USER_NAME" : "hdfs"                                                                                                
      },                                                                                                                           
      "mainClass" : "DarwinCoreToParquet",                                                                                          
      "sparkProperties" : {                                                                                                        
        "spark.driver.supervise" : "false",                                                                                        
        "spark.mesos.executor.home" : "/opt/spark/latest",                                                                         
       "spark.app.name" : "dwc2parquet",                                                                                   
        "spark.submit.deployMode" : "cluster",                                                                                     
        "spark.master" : "mesos://mesos07.acis.ufl.edu:7077",                                                                      
        "spark.executor.memory" : "20g",                                                                                           
        "spark.driver.memory" : "8g",                                                                                              
        "spark.task.maxFailures" : 1                                                                                               
      }                                                                                                                            
    } 
```
6. on completion, a parquet file should appear when listing ```hdfs dfs -ls /tmp/dwca/inaturalist/observations.csv.parquet``` . To make this data available to effechecka/freshdata, this file can be moved into partitioned directory structure available at ```hdfs:///guoda/data/gbif-idigbio.parquet/source=inaturalist/date=[YYYYMMDD]``` with date being something like 20170405, or the time at which the dwca was added, you use something like ```hdfs dfs -mv /tmp/dwca/inaturalist/observations.csv.parquet/* /guoda/data/gbif-idigbio.parquet/source=inaturalist/date=20170719``` (create the date directory -and the "source=" directory if it's new- first, using something like ```hdfs dfs -mkdir -p /guoda/data/gbif-idigbio.parquet/source=inaturalist/date=20170719```)
7. cleanup tmp folder if desired - the source dwca is not used by effechecka/freshdata .

**Comment by jhpoelen** [comment]
@jhammock I've successfully run through the above recipe after enabling dwc2parquet job to read from hdfs. I am keeping this issue open because it is a "how-to". The conversion completed in less than a minute.

**Comment by jhpoelen** [comment]
@jhammock please note that this recipe can be incorporated into existing jenkins job to automate the process at http://archive.guoda.bio . Also see https://github.com/gimmefreshdata/archive-importer .

**Comment by jhammock** [comment]
Woo! Successfully Jenproofed, see 
/guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719

**Comment by jhpoelen** [comment]
Nice! 

To double check, you might want to create a checklist / occurrence list that would include occurrences from usgsnias and confirm that they show up with mention datasource. . .

**Comment by jhpoelen** [comment]
One small note - on listing the contents of target directory:

```hdfs dfs -ls /guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719```

I found: 

```                               
Found 1 items                                                                                                                      
drwxr-xr-x   - hdfs supergroup          0 2017-07-19 17:07 /guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719/observations.txt.parquet
```

Notice that the observations.txt.parquet directory exists, instead of a list of the separate parquet files.

In order to put the parquet files directory in the ```data=20170719``` directory, please leave off the ```/``` when moving the directory. 

E.g. *not* 
```
hdfs dfs -mv [something]/observations.txt.parquet /guoda/[something]/date=20170719/
``` 
but  
```
hdfs dfs -mv [something]/observations.txt.parquet /guoda/[something]/date=20170719
```

**Comment by jhammock** [comment]
rats. After a few wrong turns I have cleaned up, retraced my steps and tried 
hdfs dfs -mv /tmp/dwca/newresource/observations.txt.parquet /guoda/data/gbif-idigbi
o.parquet/source=usgsnias/date=20170719

But I seem to have the same result.

![screen shot 2017-07-19 at 6 18 14 pm](https://user-images.githubusercontent.com/3026567/28392179-d64aa454-6cae-11e7-93a8-3954eed116d8.png)

**Comment by jhpoelen** [comment]
Hmm. After some poking around I got it to work by ```hdfs dfs -mv /tmp/dwca/newresource/observations.txt.parquet/* /guoda/data/gbif-idigbi
o.parquet/source=usgsnias/date=20170719``` . I'll update the docs. Not quite sure why it worked before ...

**Comment by jhpoelen** [comment]
@jhammock please do continue to bug me about this if there's something off.

**Comment by jhammock** [comment]
Hmm... I removed and recreated /guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719, and tried 

hdfs dfs -mv /tmp/dwca/newresource/observations.txt.parquet/* /guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719

This time I got a "_temporary/0" subdirectory inserted, with 201 items within. Is that expected? Possibly my cleanup efforts are not appropriate? I have been using -rm -r and then -mkdir at the level of /date=20170719

**Comment by jhpoelen** [comment]
Ah! Thanks for asking. The ```_temporary/0``` stuff is created while the job is running. The folder should disappear after the job is done. So, this makes me think that the job was either still running as you were copying or that it crashed for some reason. If you can provide steps to reproduce, I'd be happy to help resolve the issue.

**Comment by jhammock** [comment]
bah, I should not be allowed to transcribe things. If this comes up again it will all be awkward screenshots. Eyestrain, but with accuracy!

Anyway, I got a good night's sleep and tried again and I believe 

/guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719

Now contains expected results!

**Comment by jhammock** [comment]
Invasion of the Northern Snakehead, complete with newly added records from USGS NIAS
http://gimmefreshdata.github.io/?limit=20&taxonSelector=Channidae&traitSelector=&wktString=POLYGON%20%28%28-77.30987550225109%2038.77013452127757%2C%20-77.30987550225109%2039.10128062665259%2C%20-76.71798707451671%2039.10128062665259%2C%20-76.71798707451671%2038.77013452127757%2C%20-77.30987550225109%2038.77013452127757%29%29

**Comment by jhpoelen** [comment]
I was able to convert your earlier dwca ("newresource") successfully to parquet using documented method. For results, please see hdfs:///tmp/dwca/newresource2 . This is consistent with that the dwca2parquet process is working. If a parquet directory is move when the job is still active, it might get confused and bail out, however, I see no evidence of that. 

One thing I noticed in https://github.com/bio-guoda/guoda-services/issues/30#issuecomment-316588053 is the usage of ```//``` in the hdfs path - you might want to consider avoiding this.

Do you feel sufficiently confident in that the archive import process is ok? If not, I'd be happy to do another work session today.

**Comment by jhammock** [comment]
oops, sorry! Yes, I didn't even document my attempt last night accurately, so I'm not sure what I did, but I believe it worked perfectly this morning. If your test was in a different location, it should still be my results in /guoda/data/gbif-idigbio.parquet/source=usgsnias/date=20170719 

If those look as expected (they seem to compare well with the other resources?) then I think I'm all set!

**Comment by jhpoelen** [comment]
The described method is no longer supported. Please see https://github.com/bio-guoda/preston-scripts#preston-to-dwc-a for alternative.
