### ISSUE TITLE
Cluster is preoccupied

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#31]
I have tried the updateMonitors job a handful of times in the past day or so. A few times I've gotten success=false, and a few times I've gotten success=true, with this result:

 /guoda/data/monitor-test/occurrence/_temporary/0

which I believe is the signature of an interrupted job. Should I just keep trying?

**Comment by godfoder** [comment]
There is currently an OccurrenceCollector job running (for 1.5 hours), based on my knowledge of the system, this job will need to finish before another one will start.

**Comment by jhammock** [comment]
Ah, a FD query? OK, I will try waiting it out, but in recent history those have been taking 15 minutes.

**Comment by jhammock** [comment]
My subsequent attempt at updateMonitors has completed overnight.
