### ISSUE TITLE
update monitors fails after reconnecting to zookeeper and losing executor

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#33]
As noticed by @jhammock - update monitors started on 5 Sept 2017 around 10am eastern fails after about 9 hours around 2017-09-05 18:57:32 eastern. 

Log files stderr and stdout extracted from http://mesos02.acis.ufl.edu:5050/#/agents/dabbc59d-84c3-4fb3-8baa-045c55e020fb-S5/browse?path=%2Fvar%2Flib%2Fmesos%2Fslaves%2Fdabbc59d-84c3-4fb3-8baa-045c55e020fb-S5%2Fframeworks%2Fdabbc59d-84c3-4fb3-8baa-045c55e020fb-0000%2Fexecutors%2Fdriver-20170905125131-0260%2Fruns%2F6b416fae-17c9-4fed-8aff-99a6f018e092 are attached. Please note that the link above is not publicly accessible and is mentioned for debugging purposes only.

[stdout.txt](https://github.com/bio-guoda/guoda-services/files/1288218/stdout.txt)
[sterr.txt](https://github.com/bio-guoda/guoda-services/files/1288219/sterr.txt)

**Comment by jhammock** [comment]
Thanks, Jorrit! Yes, that datestamp corresponds my recall of starting the job.

**Comment by jhpoelen** [comment]
Looks like this is no longer an issue. Closing issue.
