### ISSUE TITLE
Policy for peer policing of GUODA resource use

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#36]
Currently a few of us have some admin access to manage activity in GUODA. It would be good to have guidelines about what constitutes a "probably idle server", based on duration of inactivity, and perhaps a communication channel among users (maybe just through github).

Also, could more users have this authority, to spread the peer-policing authority/responsibility around?

I realize this is hopefully a temporary solution, but I'm all for social engineering quick fixes until we have support for more development effort around GUODA management...

@godfoder @mjcollin @diatomsRcool @jhpoelen

**Comment by jhpoelen** [comment]
fwiw - Suggest to use this issue tracker or email to ask questions about guoda cluster.
