### ISSUE TITLE
credentials for Jenkins

### ISSUE THREAD

**Issue by diatomsRcool** [bio-guoda/guoda-services#38]
I would like to set up a Jenkins job for http://archive.guoda.bio/, but I need credentials. I assume someone at idigbio needs to give me an account?

**Comment by jhammock** [comment]
looks like you might be in there already, see http://archive.guoda.bio/asynchPeople/

**Comment by diatomsRcool** [comment]
So that means I need to remember my password....

**Comment by mjcollin** [comment]
Did you get logged in?

**Comment by diatomsRcool** [comment]
Yup
