### ISSUE TITLE
jupyter.idigbio.org responds with 503 Service Unavailable

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#4]
jupyter.idigbio.org responds with 503 Service Unavailable, see attached screenshot.

Seen on 2017-05-15 at around 16:30 (4p30) Pacific or 7p30 eastern.
![screenshot from 2017-05-15 16-28-50](https://cloud.githubusercontent.com/assets/1084872/26083660/f8dc0950-398b-11e7-8ac5-88fddbeb465f.png)

**Comment by mjcollin** [comment]
I have broken the alignment of Mesos and Spark versions while trying to get Spark to 2.1.1 to fix a path bug with HDFS. I turned off JupyterHub while that is broken.

I suppose we should set up a gateway page where we can describe the current system status...

**Comment by jhpoelen** [comment]
Looks like jupyter.idigbio.org is up and running. @mjcollin please confirm.

**Comment by mjcollin** [comment]
Err, temporary. Let me get all the configs into Salt and get everything pushed through our config management system and confirm service stability before you got to town.

**Comment by mjcollin** [comment]
Done with the Python side of #5 , need to go back to the R kernels to make sure they work.

Tentatively saying it's ok to use jupyter.idigbio.org for now. I will be restarting the service when I get to working on the R kernels.

**Comment by mjcollin** [comment]
Mesos work has been completed.
