### ISSUE TITLE
HDFS is unbalanced

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#40]
mesos01 has a full disk with the rest of the cluster only being about half full:

http://mesos02.acis.ufl.edu:50070/dfshealth.html#tab-datanode

**Comment by mjcollin** [comment]
Looks like rebalancing is manual for HDFS:

http://fibrevillage.com/storage/656-how-does-hadoop-hdfs-balance-space-usage-in-the-cluster-and-how-does-hdfs-balancer-work

Trying:

```hdfs balancer -threshold 25```

to start. Will likely need to make this a cron job on a name node.

**Comment by jhpoelen** [comment]
Looks like HDFS is happy now. Close this issue?

**Comment by mjcollin** [comment]
After recent fun w/ name node not syncing to secondary, I'm a bit cautious about cron'ing maintenance. Should not get out of balance too quickly in the future unless we do a lot of writes and deletes.
