### ISSUE TITLE
methods description of GUODA for wikidata paper

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#46]
As discussed with @diatomsRcool and promised by @mjcollin , we'd like to get a publication ready method section on guoda for future papers. Initially @mjcollin suggested to publish an independent paper, and I am wondering whether we should just have some paragraphs for inclusion in papers that use guoda to do heavy lifting (e.g., crunching all of wikidata).

**Comment by mjcollin** [comment]
Draft full paper is here. It seems I get a day every 2 weeks to touch it. I'll try to trim things to meet your expectations so I'm no longer a road-block.

https://docs.google.com/document/d/1i3VigqmOYSAjaoWGT2iYR3hVCR4iu2kN1wqgQ6Y2ahk/edit?usp=sharing

**Comment by jhpoelen** [comment]
Thanks! I also noticed that a recent paper mentioned GUODA . Would that be a fall-back reference?

James, S.A. et al., 2018. Herbarium data: Global biodiversity and societal botanical needs for novel research. Applications in Plant Sciences, p.e01024. Available at: https://doi.org/10.1002/aps3.1024.

**Comment by diatomsRcool** [comment]
I've taken information from Jorrit and Matt and put the paper together 
as much as I can for the moment.
https://docs.google.com/document/d/1WOLBUBjgGa2jmNorWLO6l6oMa8nFOIiWnFuABn3FP3Q/edit
I'm waiting on a few things from Jorrit, which we talked about a few 
days ago.
Matt, from you I would like to know why you think GUODA doesn't have 
more use. What do you see for future improvements for GUODA? Any other 
thoughts on GUODA's future, use, and uptake.
Also, Matt, if you could take a look at the paragraph describing GUODA 
in the methods and make sure I didn't screw it up, I'd appreciate it.

**Comment by mjcollin** [comment]
I've visited your paper, thank you for doing a good pass at describing GUODA.

**Comment by mjcollin** [comment]
Closing as this is done, paper nearing completion.
