### ISSUE TITLE
jupyter.idigbio.org down?

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#47]
For some reason, the jupyter.idigbio.org page says 503 service down (see attached screenshot).

@mjcollin please let me know if this is some scheduled maintenance. 
![screenshot from 2018-03-30 10-40-07](https://user-images.githubusercontent.com/1084872/38147371-e2950842-3406-11e8-80d8-12f9ba009b58.png)

**Comment by jhpoelen** [comment]
After restarting, I can see the folder/files again. However, I can't seem to open a terminal.

**Comment by jhpoelen** [comment]
After a while, the environment became responsive again and I was able to open a new terminal. Not quite sure what changed. I'll keep this issue open until things stabilize.

**Comment by mjcollin** [comment]
It does seem a bit pokey but nothing obvious is eating CPU or memory and disk IO's ok. I got a notification from the monitoring system about an hour ago about high load but that cleared in a few minutes. I'll ask Guarav if he accidentally ran work on the Jupyter server instead of the Spark cluster.

**Comment by mjcollin** [comment]
Seems to no longer be an issue
