### ISSUE TITLE
Upgrade Spark to 2.1.1 on Mesos cluster

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#5]
Upgrading Spark on Jupyterhub server and Mesos cluster because ran in to issue with Spark jobs trying to create spark-warehouse on HDFS instead of locally when submitting jobs as users other than HDFS.

**Comment by mjcollin** [comment]
Deploy via Salt to idb-jupyter1 and mesos[1-12] of Spark 2.1.1 went fine but Mesos package on idb-jupyter1 was still 0.23 which resulted in mesos1 rejecting jobs. Removed it and re-applied Salt classes to deploy Mesos 1.0.0 which matches mesos[1-12].

Still having problems submitting jobs as other users, will return to later.

**Comment by mjcollin** [comment]
mesos[1-3] elect wrong leader under most circumstances. The JupyterHub server is coded to submit to mesos1 only and if it is not the leader then jobs are not accepted. Zookeeper is the layer where this happens and the server order is specified with mesos2 as the first server in the configs. This isn't documented to be a strict ordering but probably they are tried sequentially so there is a preference. Zookeeper administration guide documents groups and weights as the way to specify preference, updating configs in Salt.

**Comment by mjcollin** [comment]
Weights for Zookeeper are for grouping hosts for quorum, not preferring a leader. The issue with leader flux is that the host new spark frameworks are submitted to needs to be specified in a .json file for JupyterHub. This means there isn't an opportunity to update the host dynamically when the leader changes without scripting.

The kernel .json file also has a hard-coded import for py4j which changes versions periodically with Spark. Probably the best route there is to have the Spark Salt class maintain a py4j-latest symlink that can be used in the kernel config.

Good news, Spark 2.1.1 runs fine under the existing Jupyterhub config if these things are manually aligned. Just need a maintainable path now.

**Comment by jhpoelen** [comment]
interesting ... can't you just provide a list of possible leaders and let jupyter figure out which one to use?

**Comment by mjcollin** [comment]
http://stackoverflow.com/questions/29515288/identify-live-spark-master-at-the-time-of-spark-submit

Looks like I can do a comma separated list. I'll give it a try.

**Comment by mjcollin** [comment]
Docs are different syntax from above stackoverflow post, note Zookeeper syntax:

http://spark.apache.org/docs/latest/running-on-mesos.html#connecting-spark-to-mesos

`--master mesos://zk://mesos01:2182,mesos02:2181,mesos03:2181/mesos`

**Comment by mjcollin** [comment]
Re-worked Python kernels with templates in Salt that are "right-sized" according to cluster size and use syntax to submit to the current Zookeeper master to support Mesos leader changes.

The names of the Python kernels have changed but Jupyter seems to nicely prompt you to pick a new kernel when you open a notebook with an older kernel name. 

Leaving open until R kernels are tested and working.

**Comment by jhpoelen** [comment]
@mjcollin just successfully connected to cluster using terminal scala spark shell using -

```
/opt/spark/spark-2.1.1-bin-hadoop2.7/bin/spark-shell --master mesos://zk://mesos01:2182,mesos02:2181,mesos03:2181/mesos            
```

unfortunately, when I was trying to run my https://gist.github.com/jhpoelen/18b5ffe083f32dd1dca360a83e34cfd3 ... not enough resources were available. Would be nice to have some public page answering the questions : how busy is the server and who's using it.

**Comment by mjcollin** [comment]
R notebooks work, but having different issues related to constraining resource usage so closing this. @jhpoelen - Moving your last comment to a new request.
