### ISSUE TITLE
enable https for guoda.bio site

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#51]
visiting https://guoda.bio causes certificate issues.

github now allows for custom domains to use https via github pages:
see 
https://help.github.com/articles/troubleshooting-custom-domains/#https-errors
and 
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by mjcollin** [comment]
I'm changing the DNS settings for the domain which should be able to fix this:

> If you are using A records, you must update your site’s DNS records with new IP addresses. Please see our guide to setting up your custom domain with Pages and update any A records you might have set.

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by jhpoelen** [comment]
I was able to check  the "enable https" via https://github.com/bio-guoda/bio-guoda.github.io/settings (see screenshot attached) 
![Screenshot from 2019-09-13 15-51-57](https://user-images.githubusercontent.com/1084872/64899083-889fc800-d63e-11e9-9419-ae425e2e9b0f.png)

However, after enabling, the following error message was shown in my browser (see attached screenshot): 

```
This site can’t be reached
The webpage at https://guoda.bio/ might be temporarily down or it may have moved permanently to a new web address.

ERR_FAILED
```

![Screenshot from 2019-09-13 15-53-49](https://user-images.githubusercontent.com/1084872/64899145-db797f80-d63e-11e9-8581-a161dd3b63d0.png)

**Comment by jhpoelen** [comment]
Looks like the https transition errors were temporary. After update of base url in jekyll config https://github.com/bio-guoda/bio-guoda.github.io/commit/ca2865abd9d939cef3ed7de7c69e60eb5b29f162 the site is now ok loading via https://guoda.bio . 

![Screenshot from 2019-09-13 16-18-06](https://user-images.githubusercontent.com/1084872/64899859-4ed0c080-d642-11e9-8373-9c6e1bca8615.png)
