### ISSUE TITLE
marathon no longer running, causing api outage

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#52]
Marathon, the service that runs the api and spark job dispatcher, is no longer running for reasons unknown.

**Comment by mjcollin** [comment]
Seems to have lost consistency:

```
HTTP ERROR: 503
Problem accessing /. Reason:

    Could not determine the current leader
Powered by Jetty:// 9.3.z-SNAPSHOT
```

Restart on all nodes has brought it back up. Two possible causes: the last logs were requests from the UFIT security scanner (a classic destroyer of services) and Tuesday I filled up HDFS for about an hour though Marathon proper doesn't use HDFS for anything, only it's services do.

**Comment by jhpoelen** [comment]
Thanks for responding. Looks like marathon and the api are back up, see attached. 
![screenshot from 2018-07-05 07-44-03](https://user-images.githubusercontent.com/1084872/42330155-50673108-8027-11e8-9515-40b34b68eebf.png) . Curious to learn more about the root causes.
