### ISSUE TITLE
how can I check on a makeparquet task?

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#55]
I've been waiting ~4 hours for a parquet file to appear in /tmp/dwca/newresource/, which is dramatically longer than it usually takes (to make a parquet of the two files currently in that directory). The command I usually use was met with "success: true", so I presume it's possible this task is still running. Is there a way I can check on it?

**Comment by jhammock** [comment]
I would still like to know the answer to this question, but I eventually repeated this task and it ran normally

**Comment by jhpoelen** [comment]
@jhammock my intuition about this is that an effechecka job was processing and your dwca conversion job got rejected. Having a queuing mechanism (see #28) with a view on the queue would help to (1) ensure that the job gets run eventually and (2) get some view into the job execution mechanism. Curious to hear your thoughts.

**Comment by jhammock** [comment]
a visible queue would entirely meet my particular needs, yes. I can see a number of things already in Jenkins and wasn't sure what I needed wasn't in there somewhere already...

**Comment by mjcollin** [comment]
Likely root cause is #59 
Can I close?
