### ISSUE TITLE
failed job, update monitors

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#58]
Jenkins reports my second attempt to run http://archive.guoda.bio/job/update%20monitors/  has failed. I daresay that may mean it has crashed something in GUODA again.

**Comment by jhpoelen** [comment]
This, and the fact that effechecka.org is no longer showing checklists, is consistent with the behavior that the upgrade monitor job makes the hdfs cluster inaccessible #57 . @mjcollin - please confirm. 

Suggest to close this issue as a duplicate #57 .

**Comment by jhpoelen** [comment]
Thanks! @diatomsRcool @jhammock @mjcollin I'll put the hdfs stability issue on the agenda for next GUODA meeting. Hopefully, we'll figure out a way to resolve the issue before that.
