### ISSUE TITLE
Enable Scala notebooks in JupyterHub

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#6]

**Comment by jhpoelen** [comment]
Was hoping to show https://gist.github.com/jhpoelen/18b5ffe083f32dd1dca360a83e34cfd3 off in a scala notebook  . . . let me know when you'd like me to try it!

**Comment by mjcollin** [comment]
I'm trying https://github.com/alexarchambault/jupyter-scala

```
Jun  2 15:37:49 idb-jupyter1 jupyterhub[15398]: [D 2017-06-02 15:37:46.763 mjcollin manager:241] Starting kernel: ['java', '-noverify', '-jar', '/usr/local/share/jupyter/kernels/scala/launcher.jar', 'launch', '-r', 'sonatype:releases', '-r', 'sonatype:snapshots', '-i', 'ammonite', '-I', 'ammonite:org.jupyter-scala:ammonite-runtime_2.11.11:0.8.3-1', '-I', 'ammonite:org.jupyter-scala:scala-api_2.11.11:0.4.2', 'org.jupyter-scala:scala-cli_2.11.11:0.4.2', '--', '--id', 'scala', '--name', 'Scala', '--jupyter-path', '/usr/local/share/jupyter', '--global', '--quiet', '--connection-file', '/home/mjcollin/.local/share/jupyter/runtime/kernel-2b89d4a2-003e-434f-b478-85a822f22141.json']
Jun  2 15:37:49 idb-jupyter1 jupyterhub[15398]: Error: Unable to access jarfile /usr/local/share/jupyter/kernels/scala/launcher.jar
```

The "just run this simple command!" installer seems to put a bunch of stuff it gets from maven under /root/.coursier even when I tell it where jupyter is and give it the --global flag to write the kernel.json correctly under /usr/share/jupyter/kernels. Do I need to get that pile of .jars in /root/.coursier out to some globally accessible place like somewhere under JAVA_HOME?

**Comment by jhpoelen** [comment]
Default maven dir is ~/.m2 . Not quite sure what .coursier means. From what I can tell, the maven install calculates location based on installation directory and shoves dependencies into ~/.m2/repository by default. You can change settings.xml to point repository to a share spot. I hope this helps . . . I wish I was a little more familiar with jupyter notebooks...

**Comment by jhpoelen** [comment]
hey @mjcollin - just tried to start a scala jupyter notebook for some wiki data examples / linking. For some reason, the kernel crashes after starting (see screenshot). Would this be easy to fix?

![screenshot from 2018-03-14 10-16-12](https://user-images.githubusercontent.com/1084872/37419151-0c3e08f8-2771-11e8-8bcb-327359ad26e1.png)

**Comment by jhpoelen** [comment]
I mostly work in ```spark-shell``` or related scala IDEs . No need for scala jupyter notebooks for now, unless others have a desire.
