### ISSUE TITLE
Cleaning up temporary and misc job files on cluster

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#60]
The disks collect junk in a couple places:

1. /tmp - sbt<id>.log, typically ~5 MB

Fixed with:
`echo` "find /tmp -type f -atime +14 -delete" > /etc/cron.daily/tmp_clean && chmod 0755 /etc/cron.daily/tmp_clean`

2. /var/lib/docker/aufs/diff

Looks like diffs of the running images for efechecka, newer versions of docker have better tools for cleaning these, wait for later.

3. /var/lib/mesos/slaves/<id>/frameworks

Old frameworks can be removed however need to know if they're currently running, can't just clean old files.

**Comment by mjcollin** [comment]
Nodes are full again w/o HDFS being full (although it's at 87%). Specifically when looking at mesos01:

1. Cron to clean out /tmp is working fine, only a few MB there
1. Still not cleaned out but only about 3-5 GB (on 900 GB disks) there, not much reward
1. Old frame works seem to be getting cleaned, only a few MB there

/var/log looks like the culprit this time. Tens of GB in hadoop, journal, and mesos.

**Comment by mjcollin** [comment]
Added lines to clean /var/log/hadoop and /var/log/mesos of logs older than 60 days to free up a little space quickly.

Mid-term plan, get more stuff off of HDFS by archiving and write out iDigBio monthly instead of weekly to put less stuff on.

**Comment by jhpoelen** [comment]
Nice!

**Comment by jhpoelen** [comment]
Closing stale issue.
