### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by diatomsRcool** [bio-guoda/guoda-services#64]
Well now I can't even log in. I get the following.
"POST is required for hudson.model.AbstractProject.doConfigSubmit"
with a "Try POSTing" button below it. When I hit that button I get a 403 error with the reason "no valid crumb was included in the request"

**Comment by jhpoelen** [comment]
@mjcollin perhaps a nice issue for Icaro to get started on .
@diatomsRcool could you please add some more details like steps to reproduce the issue and expected and actual behavior like. For example, see https://testlio.com/blog/the-ideal-bug-report/ .

**Comment by diatomsRcool** [comment]
ok, well, I'm on a mac using Chrome
I expect to type in my username and password and hit "log in" and be properly logged in. Instead I get the POST message above. This happens whether I choose "remember me on this machine" or not. I'm trying to log in to jenkins.
<img width="730" alt="screen shot 2019-01-10 at 10 42 13 am" src="https://user-images.githubusercontent.com/5140552/50979435-70324900-14c4-11e9-8c88-3830ed24ed7b.png">
<img width="742" alt="screen shot 2019-01-10 at 10 42 47 am" src="https://user-images.githubusercontent.com/5140552/50979460-7f18fb80-14c4-11e9-86a9-8674cf1426fb.png">

**Comment by diatomsRcool** [comment]
Well now it says I'm logged in, so I really don't know what's happening here

**Comment by jhpoelen** [comment]
Hmm. Interesting, @mjcollin @ialzuru any idea what is going on?

**Comment by jhpoelen** [comment]
Closing stale issue.
