### ISSUE TITLE
no progress on job

### ISSUE THREAD

**Issue by diatomsRcool** [bio-guoda/guoda-services#65]
I've had the ecoregions job running for several weeks and the number of 503s in the checklist_status.tsv file has not decreased. 
http://archive.guoda.bio/job/ecoregion%20status%20checker/
When I search the checklist_status.tsv file for ' 102' to find the query that is currently being worked on, I don't get any results. This makes me think that nothing is in process and that's why no progress has been made. What could be preventing effechecka from accepting new jobs?

**Comment by jhpoelen** [comment]
@diatomsRcool When filing an issue, please follow the template as outlined on https://testlio.com/blog/the-ideal-bug-report/ . Please attach the checklist_status.tsv to this issue as evidence. Also, please be specific on which url you use to access the status checker tsv.

**Comment by diatomsRcool** [comment]
Chrome on a mac
check the file in between builds so the file is fully formed. There should be around 14K lines.
http://archive.guoda.bio/job/ecoregion%20status%20checker/ws/checklist_status.tsv/*view*/
I do a ctl-f search for "503" to see how many queries are left. I expect that number to go down over time. It has not.
I expect to be able to find one or two queries with a 102 status, but I cannot.
Below is an example URL for downloading a checklist
curl -o checklist/1.tsv "http://api.effechecka.org/checklist.tsv?wktString=POLYGON((-112.27%2029.326%2C%20-112.288%2029.326%2C%20-112.302%2029.322%2C%20-112.314%2029.32%2C%20-112.321%2029.317%2C%20-112.325%2029.316%2C%20-112.329%2029.317%2C%20-112.333%2029.32%2C%20-112.337%2029.32%2C%20-112.344%2029.314%2C%20-112.347%2029.316%2C%20-112.35%2029.318%2C%20-112.35%2029.32%2C%20-112.35%2029.323%2C%20-112.349%2029.329%2C%20-112.346%2029.333%2C%20-112.343%2029.34%2C%20-112.337%2029.349%2C%20-112.335%2029.354%2C%20-112.332%2029.357%2C%20-112.327%2029.362%2C%20-112.323%2029.365%2C%20-112.318%2029.367%2C%20-112.311%2029.367%2C%20-112.305%2029.366%2C%20-112.301%2029.364%2C%20-112.289%2029.356%2C%20-112.282%2029.352%2C%20-112.277%2029.347%2C%20-112.274%2029.344%2C%20-112.271%2029.339%2C%20-112.268%2029.335%2C%20-112.267%2029.331%2C%20-112.27%2029.326))"

Below is a URL for checking the status of a check list
echo "geonames_id\\tchecked_at\\thttp_status_code" > checklist_status.tsv
curl -s -o /dev/null -w "%{http_code}" "http://api.effechecka.org/checklist.tsv?limit=1&wktString=POLYGON((-112.27%2029.326%2C%20-112.288%2029.326%2C%20-112.302%2029.322%2C%20-112.314%2029.32%2C%20-112.321%2029.317%2C%20-112.325%2029.316%2C%20-112.329%2029.317%2C%20-112.333%2029.32%2C%20-112.337%2029.32%2C%20-112.344%2029.314%2C%20-112.347%2029.316%2C%20-112.35%2029.318%2C%20-112.35%2029.32%2C%20-112.35%2029.323%2C%20-112.349%2029.329%2C%20-112.346%2029.333%2C%20-112.343%2029.34%2C%20-112.337%2029.349%2C%20-112.335%2029.354%2C%20-112.332%2029.357%2C%20-112.327%2029.362%2C%20-112.323%2029.365%2C%20-112.318%2029.367%2C%20-112.311%2029.367%2C%20-112.305%2029.366%2C%20-112.301%2029.364%2C%20-112.289%2029.356%2C%20-112.282%2029.352%2C%20-112.277%2029.347%2C%20-112.274%2029.344%2C%20-112.271%2029.339%2C%20-112.268%2029.335%2C%20-112.267%2029.331%2C%20-112.27%2029.326))"| xargs echo 1\	$(date -Is)\	 >> checklist_status.tsv

**Comment by diatomsRcool** [comment]
As far as I can tell, its using this script to get the status and do the download
https://github.com/effechecka/effechecka-scripts/blob/master/checklist_script_gen.sh

**Comment by jhpoelen** [comment]
thanks for providing the links and scripts. In addition, I've attached a version of the checklist_status.tsv I just downloaded from http://archive.guoda.bio/job/ecoregion%20status%20checker/ws/checklist_status.tsv as supporting evidence, see attached. 

using 
```console
$ cat checklist_status.txt | wc -l
5817 
$ cat checklist_status.txt | grep "503$" | wc -l
50
```
I determined that 50 checklist items out of (5817 -1) are in status 503. 

Please confirm this is consistent with what you are seeing.

If so, the next step would be to figure out why checklists with ids 

```9813 9837 9838 9839 9849 9850 9851 9886 9887 9888 9889 9891 9894 9897 9898 9899 9900 9918 9919 9921 9990 9991 9999 10000 10001 10003 10004 10006 10007 10008 10011 10012 10081 10082 10276 10277 10282 10284 10286 10287 10335 10336 10337 10339 10340 10341 10419 10420 10427 10429 ```

are not getting processed . 

[checklist_status.txt](https://github.com/bio-guoda/guoda-services/files/2770205/checklist_status.txt)

**Comment by diatomsRcool** [comment]
The first problem I see is that 
$ cat checklist_status.txt | wc -l
should return something more like 14000

I think the script is not finished writing.

**Comment by diatomsRcool** [comment]
I'm turning the builds off for now

**Comment by jhpoelen** [comment]
Ah ok, good to know. This is why I like working with specific examples instead of urls. Perhaps a way to work around this is to have a checklist_status_previous.tsv and checklist_status_processing.tsv , where once the checklist_status_processing.tsv gets copied to checklist_status_previous.tsv once the list is complete. Let me know if you need some help to add this to the existing script.

**Comment by diatomsRcool** [comment]
have a look at it now. It's up to date.

**Comment by jhpoelen** [comment]
At a quick glance, only 8716 lines are included in the status check file. Please attach the up-to-date file to make sure we are looking at the same thing.

**Comment by diatomsRcool** [comment]
I have no idea how to do half of what you are asking me to do. 
https://www.dropbox.com/s/s03gpj3tzlezki0/checklist_status%20%281%29.tsv?dl=0
A dropbox link is the best I can do

**Comment by jhpoelen** [comment]
I was hoping you could attach the file to this github issue. Attaching the file to a github issue help me to keep track of what we are talking about.

**Comment by jhpoelen** [comment]
Inspecting your file on dropbox confirm that the status file only contains 8716 lines, instead of your expected 14000 lines. Any idea which checklists are missing?

**Comment by diatomsRcool** [comment]
OK, so that's weird because when I look at it using the "view" link
http://archive.guoda.bio/job/ecoregion%20status%20checker/ws/checklist_status.tsv/*view*/
There are 14911 queries.
I checked the list of wkt strings to make sure this was correct and there are 14911 wkt strings. I don't understand why the download is not grabbing the entire file.

**Comment by jhpoelen** [comment]
I can see how the last line of both the downloaded and view link contains:

```14911   2019-01-17T14:26:57-05:00        200```

However, the geonames ids are not continuous sequence of increasing integers. Instead it looks like there's gaps. For instance, the first lines contain:

```
geonames_id\tchecked_at\thttp_status_code
1       2019-01-17T12:15:51-05:00        200
2       2019-01-17T12:15:51-05:00        200
5       2019-01-17T12:15:51-05:00        200
7       2019-01-17T12:15:51-05:00        200
8       2019-01-17T12:15:51-05:00        200
9       2019-01-17T12:15:51-05:00        200
```
Note that 3,4,6 are missing. Is that expected?

**Comment by jhpoelen** [comment]
Hey @diatomsRcool - I just checked the cluster earlier and found that there were two pyspark shells hoarding all the resources. This explains why your checklists didn't make any progress. Perhaps @mjcollin or @ialzuru have some ideas on how to make it easier for all of us to apply the cluster "drano" (https://en.wikipedia.org/wiki/Drano) when it's clogged. A little view on cluster usage and activitiy combined with a big red "drano" / unclog button. 

I took the liberty to re-enable your checklist job at http://archive.guoda.bio/job/ecoregion%20status%20checker

**Comment by jhpoelen** [comment]
btw - in looking at your checklist status update script - it takes about 2 hours to scan all the 8k checklist each time while it take about 20 min to generate a checklist. You might want to restrict checking lists that were previously non-200 status.

**Comment by jhpoelen** [comment]
@diatomsRcool I just spent 30 mins implementing an optimization to only check checklists that were previously in a non-200 status. For code see https://github.com/effechecka/effechecka-scripts/commit/9d188c3f80cbe4d4c0dee8e442e022318de5ad6f . Also, as far as I can tell, checklists are getting generated and progress is being made. Please confirm and close issue.

**Comment by diatomsRcool** [comment]
Thank you so much! It looks like its back to working again.
