### ISSUE TITLE
Advice, please, for a GUODA job that often fails

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#66]
I've heard that I have the access necessary to get myself unstuck when I have a job I can't get to succeed in the GUODA architecture. If someone could advise me, I'd appreciate it. I often get stuck lately at this point:

`jhammock@idb-jupyter1:~$ unzip -p gbif-observations-dwca.zip meta.xml | hdfs dfs -put - /tmp/dwca/newresource/meta.xml

jhammock@idb-jupyter1:~$ unzip -p gbif-observations-dwca.zip observations.csv | hdfs dfs -put - /tmp/dwca/newresource/observations.csv

jhammock@idb-jupyter1:~$ curl -X POST http://mesos07.acis.ufl.edu:7077/v1/submissions/create --header "Content-Type:application/json;charset=UTF-8" --data @makeparquet.json

{                                                                                                           
  "action" : "CreateSubmissionResponse",                                                                    
  "message" : "Already reached maximum submission size",                                                    
  "serverSparkVersion" : "2.2.0",                                                                           
  "success" : false`

**Comment by jhpoelen** [comment]
Thanks for sharing! Looks like the cluster is too busy to handle additional requests, so it doesn't attempt to run the request. 

To run do the same thing locally (in your customary terminal at jupyter.idigbio.org ) : 

```console
$ wget https://s3-us-west-2.amazonaws.com/guoda/idigbio-spark/iDigBio-LD-assembly-1.5.9.jar                                                                                                      
$ spark-shell --jars iDigBio-LD-assembly-1.5.9.jar --class DarwinCoreToParquet file:///home/jhpoelen/tmp/meta.xml                                                                                
[...]
[file:///home/jhpoelen/tmp/meta.xml] reading... done.                                                       
[file:///home/jhpoelen/tmp/taxa.txt] loading... done.                                                       
file:///home/jhpoelen/tmp/taxa.txt.parquet                                                                  
 done.                                     
```
where, you'd want to replace ```file:///home/jhpoelen/tmp/meta``` with your favorite path of your meta.xml (e.g., ```hdfs:///tmp/dwca/newresource/meta.xml```)

**Comment by jhpoelen** [comment]
@diatomsRcool note that similar approach can be taken to calculate checklists by using ```--class ChecklistGenerator``` with appropriate arguments.

**Comment by jhammock** [comment]
Thanks, @jhpoelen ! So I think I normally run this process on a directory containing the meta file and a tabulated file of occurrence records. Should I run the DarwinCoreToParquet command on each file separately? That doesn't seem likely to yield the same result. In other words, I'm not sure in your example above how the command reaches the /taxa.txt file.

**Comment by jhpoelen** [comment]
In the example I used, the taxa.txt is the "core" table in meta.xml . For occurrence datasets, this "core" table is usually called ```occurrences.txt``` or similar. The example I used was some kind of checklist archive with "taxa.txt" as core table. 

In your example, ```$ unzip -p gbif-observations-dwca.zip observations.csv | hdfs dfs -put - /tmp/dwca/newresource/observations.csv``` is a way to not have to unpack all the files in the zip and only shove the content of ```observations.csv``` straight into hdfs. Note that for ```gbif-observations-dwca.zip```, the meta.xml should specify ```observations.csv``` as the core table. Please confirm.

**Comment by jhammock** [comment]
Yes, the two files are from an archive of which observations.csv is the core. (not the only table, in this case; there was a media table.) The two files are now together in a directory. So the path I should use is the path to the meta file, in that directory?

**Comment by jhpoelen** [comment]
Yep. In your example above, you'd use ```/tmp/dwca/newresource/meta.xml``` or, more precisely, ```hdfs:///tmp/dwca/newresource/meta.xml``` (notice the three slashes).

**Comment by jhammock** [comment]
OK, below is the result. I think I've still misunderstood something if I'm meant to be doing this locally. The location of my temporary directory is, I think, in hdfs...

`jhammock@idb-jupyter1:~$ wget https://s3-us-west-2.amazonaws.com/guoda/idigbio-spark/iDigBio-LD-assembly-1.5.9.jar

--2019-01-30 12:05:29--  https://s3-us-west-2.amazonaws.com/guoda/idigbio-spark/iDigBio-LD-assembly-1.5.9.jar                       
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.216.144                                                 
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.216.144|:443... connected.                             
HTTP request sent, awaiting response... 200 OK                                                                                      
Length: 47710815 (46M) [application/java-archive]                                                                                   
Saving to: 'iDigBio-LD-assembly-1.5.9.jar'                                                                                          
                                                                                                                                    
iDigBio-LD-assembly-1.5.9.jar    100%[==========================================================>]  45.50M  1.55MB/s    in 62s      
                                                                                                                                    
2019-01-30 12:06:31 (757 KB/s) - 'iDigBio-LD-assembly-1.5.9.jar' saved [47710815/47710815]                                          
                                                                                                                                    
jhammock@idb-jupyter1:~$ spark-shell --jars iDigBio-LD-assembly-1.5.9.jar --class DarwinCoreToParquet file:///tmp/dwca/newresource/meta.xml                    
                                                                                                         
19/01/30 12:09:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where 
applicable                                                                                                                          
19/01/30 12:09:51 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.                                  
19/01/30 12:09:51 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.                                  
[file:///tmp/dwca/newresource/meta.xml] reading...                                                                                  
failed due to: [Path does not exist: file:/tmp/dwca/newresource/meta.xml;]    `

**Comment by jhpoelen** [comment]
instead of using file:///tmp/dwca... use hdfs:/// .

**Comment by jhpoelen** [comment]
(assuming that's where your meta.xml file lives)

**Comment by jhammock** [comment]
So the files are on hdfs but the computation is running locally? I think it's working:

`jhammock@idb-jupyter1:~$ spark-shell --jars iDigBio-LD-assembly-1.5.9.jar --class DarwinCoreToParquet hdfs:///tmp/dwca/newresource/meta.xml
                                                
19/01/30 12:20:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where  applicable                                                                                                                          
19/01/30 12:20:35 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.                                  
19/01/30 12:20:35 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.                                  
[hdfs:///tmp/dwca/newresource/meta.xml] reading... done.                                                                            
[hdfs:///tmp/dwca/newresource/observations.csv] loading... done.                                                                    
[hdfs:///tmp/dwca/newresource/observations.csv.parquet] saving...19/01/30 12:20:48 WARN Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.         
[Stage 3:=======================>                                                                                      (7 + 4) / 33]
       `

**Comment by jhpoelen** [comment]
Yep, looks like your files are in hdfs and you are running a local spark instance in your jupyter terminal. Curious to see the end result. Also, I am hoping you can help write a little how-to on this so that we can remember / share with others.

**Comment by jhpoelen** [comment]
btw - notation (7 + 4) / 33 means: 7 out of 33 stages done using 4 parallel processes .

**Comment by jhammock** [comment]
Success! I'll try to start a wiki page but it'll need more informed input. Stand by.
                                                      
jhammock@idb-jupyter1:~$ spark-shell --jars iDigBio-LD-assembly-1.5.9.jar --class DarwinCoreToParquet hdfs:///tmp/dwca/newresource/meta.xml    

19/01/30 12:20:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where  applicable                                                                                                                          
19/01/30 12:20:35 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.                                  
19/01/30 12:20:35 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.                                  
[hdfs:///tmp/dwca/newresource/meta.xml] reading... done.                                                                            
[hdfs:///tmp/dwca/newresource/observations.csv] loading... done.                                                                    
[hdfs:///tmp/dwca/newresource/observations.csv.parquet] saving...19/01/30 12:20:48 WARN Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.         
hdfs:///tmp/dwca/newresource/observations.csv.parquet                                                                               
 done.                                                                                                                              
jhammock@idb-jupyter1:~$ hdfs dfs -ls /tmp/dwca/newresource                                                                         
Found 3 items                                                                                                                       
-rw-r--r--   3 hdfs supergroup       4106 2019-01-29 14:08 /tmp/dwca/newresource/meta.xml                                           
-rw-r--r--   3 hdfs supergroup 4415914255 2019-01-29 14:10 /tmp/dwca/newresource/observations.csv                                   
drwxr-xr-x   - hdfs supergroup          0 2019-01-30 12:29 /tmp/dwca/newresource/observations.csv.parquet

**Comment by jhammock** [comment]
as threatened, here is [a wiki page](https://github.com/bio-guoda/guoda-services/wiki/Sample-job:-adding-or-removing-data-from--guoda-data).  I suspect you both have wiki edit access if you're interested in filling in some of the ????? bits and generally making it make more sense.
