### ISSUE TITLE
A 3 month old job *might* still be running

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#67]
Jenkins seems to think [this job](http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/121/) from late October might still be running, thugh two aborts are also documented. If it's not actually running, I guess this is not an issue. I'm just reporting in case this is tying up resources.

**Comment by jhpoelen** [comment]
Just confirmed that the job is no longer running.
