### ISSUE TITLE
Fresh Data updateMonitors job did not result in data availability

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#68]
I just tried a reharvest of iNaturalist data followed by an update monitors job which thinks it completed. http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/ 

Fresh Data queries are still coming up empty: http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

**Comment by jhpoelen** [comment]
Thanks for sharing. Because it finished relatively recently, I was able to uncover the root cause from the logs: hdfs ran out of space. We need a bigger boat or do some spring cleaning. 

@ialzuru any ideas on how to handle this?

I've attached the log from mesos01:5050 file for future reference. 
[stderror.txt](https://github.com/bio-guoda/guoda-services/files/2887545/stderror.txt)

**Comment by jhpoelen** [comment]
Note that hdfs is used to store both the datasets as well as the monitor results.

**Comment by jhpoelen** [comment]
On a close look, disk outage may have also caused by a worker node mesos09. I don't have access to the worker nodes, so can't check the disk usage. 

stacktace:
```
Lost task 2199.0 in stage 5.0 (TID 2727, mesos09.acis.ufl.edu, executor 6): java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at org.apache.spark.storage.TimeTrackingOutputStream.write(TimeTrackingOutputStream.java:58)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseBufferedOutputStream$1.org$apache$spark$storage$DiskBlockObjectWriter$ManualCloseOutputStream$$super$close(DiskBlockObjectWriter.scala:105)
	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseOutputStream$class.manualClose(DiskBlockObjectWriter.scala:63)
	at
```

**Comment by ialzuru** [comment]
Yesterday I checked the problem you reported a couple of days ago. The cluster has space problems. 
DFS Remaining: 1361937262080 (1.24 TB)
DFS Used: 8360191356928 (7.60 TB)
DFS Used%: 85.99%

Node 11 is not working because the file system is in read-only mode, and node 9 is completely full, that is why is generating the error. 
I do not know what is the information we have there. Can part of that data be stored somewhere else? Or we need them all in the cluster? 
All the nodes seem to work with a single 1TB HGST drive. OS and Data in the same physical drive (Ideally, they should be separated).
Physically, I do not know if these machines can be expanded.

**Comment by ialzuru** [comment]
Nicholas Rejack confirmed mesos1-6 machines are physical nodes. 
He is locating the remaining nodes at the moment.
He believes Node 11 is not responding because its drive is in pre-failure mode.

**Comment by jhpoelen** [comment]
@ialzuru thanks for sharing your and Nicholas @nrejack observations!

**Comment by jhpoelen** [comment]
HDFS today is 67% full after removing older versions of BHL (biodiversity heritage library)

```
$ hdfs dfs -df -h                                                                    
Filesystem            Size   Used  Available  Use%                                                          
hdfs://hdfscluster  10.4 T  7.0 T      2.7 T   67%       
```

~ 1.9TB is devoted to idigbio backups
```
$ hdfs dfs -du -s  /guoda/data/idigbio* | awk 'BEGIN {FS = " "}; {sum+=$1} END {print
 sum/1024/1024/1024}'                                                                                       
1879.81                
```


~ 165 GB contains freshdata source data (e.g., gbif,  etc)
```
hdfs dfs -du -s  /guoda/data/gbif* | awk 'BEGIN {FS = " "}; {sum+=$1} END {print su
m/1024/1024/1024}'                                                                                          
165.618                  
```

**Comment by jhpoelen** [comment]
Please note that I just re-opened  https://github.com/gimmefreshdata/freshdata/issues/85 due to apparent HDFS failures.

**Comment by jhpoelen** [comment]
Another error log indicating hdfs write issues: 

```
19/03/08 12:20:14 WARN RetryInvocationHandler: Exception while invoking class org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.delete over mesos02.acis.ufl.edu/10.13.44.18:8020. Not retrying because failovers (15) exceeded maximum allowed (15)
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category WRITE is not supported in state standby
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:87)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1774)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1313)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.delete(FSNamesystem.java:3711)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.delete(NameNodeRpcServer.java:947)
```

**Comment by jhpoelen** [comment]
After @ialzuru and @nrejack helped resolve the HDFS issues, an updateMonitors job was completed successfully. See attached logs. 

[stdout-driver-updateMonitors.txt](https://github.com/bio-guoda/guoda-services/files/2989064/stdout-driver-updateMonitors.txt)
[stderr-driver-updateMonitors.txt](https://github.com/bio-guoda/guoda-services/files/2989065/stderr-driver-updateMonitors.txt)

**Comment by jhpoelen** [comment]
Note that @jhammock reduced the amount of active monitors as a workaround for  https://github.com/gimmefreshdata/freshdata/issues/86 . This would have likely sped up the update because less work was needed to update/populate the monitors.

**Comment by jhammock** [comment]
Expected data are now showing in several monitors after the latest updateMonitors job.

**Comment by jhammock** [comment]
FYI, the next updateMonitors job is running now. It's been going for about 40 hours, but apart from that, no sign that anything is wrong.
