### ISSUE TITLE
updateMonitors job is 10x slower than last time

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#69]
The current updateMonitors job, started March 26 at 1:15pm, has now been running for 70 hours. 

I could work with slow jobs if that's just how it is, but since the last run completed in 7 hours, I expect this might mean something is wrong.

**Comment by jhpoelen** [comment]
Thanks for sharing. I checked the logs for the updateAll job and noticed that it completed successfully. Also, the service url normally used by the jenkins job to check on the status of the job is indicating that the job finished. So, this leads me to conclude that either the script that polls the status of the job or the jenkins logic is misbehaving somewhat. Suggest to open a new issue to indicate that the jenkins updateAll job is not correctly updating the status of the job. 

I've attached some screenshots . 

![Screenshot from 2019-03-29 08-53-12](https://user-images.githubusercontent.com/1084872/55245556-9da7ac80-5200-11e9-81c5-4316756ccdac.png)
![Screenshot from 2019-03-29 08-50-38](https://user-images.githubusercontent.com/1084872/55245557-9da7ac80-5200-11e9-8975-8c656e50155b.png)

**Comment by jhammock** [comment]
can do. Is that a GUODA services issue?

**Comment by jhpoelen** [comment]
I suspect that the program "curl" in the monitor bash script stalled due. Suggest to include a timeout to avoid the script from stalling. https://unix.stackexchange.com/questions/94604/does-curl-have-a-timeout/94612 . You can add the timeout parameter by updating the bash script in https://github.com/gimmefreshdata/archive-importer/blob/master/archives.groovy#L90 .
