### ISSUE TITLE
Update R kernels on Jupyter hub to connect to Mesos w/ Zookeeper

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#7]
See comment in #5

**Comment by mjcollin** [comment]
SparkR kernel does not start at all even with new Zookeeper connection string. Interactive kernels start on idb-jupyter1 but not when trying to use the irkernel for Jupyter. @saumitraaditya

**Comment by mjcollin** [comment]
Still haven't gotten the ir kernel working under Jupyter yet but as a work-around, you can run an interactive session from the terminal:

1. Log in to jupyter.idigbio.org and start a new terminal (dropdown in upper right)
1. Start a SparkR session with 
```
SPARK_HOME="/opt/spark/latest" HADOOP_CONF_DIR="/etc/hadoop/conf" HADOOP_USER_NAME="hdfs" /opt/spark/latest/bin/sparkR --master mesos://zk://mesos02:2181,mesos01:2181,mesos03:2181/mesos
```
all as one command
1. Try these two lines to make sure things are working:
```
df <- read.df("/guoda/data/idigbio-20161119-100k.parquet") 
dim(df)
```

**Comment by mjcollin** [comment]
Don't use above line to start R since it has no limit on the cores and will allocate the whole cluster. Use this line instead:
```
SPARK_HOME="/opt/spark/latest" HADOOP_CONF_DIR="/etc/hadoop/conf" HADOOP_USER_NAME="hdfs" /opt/spark/latest/bin/sparkR --master mesos://zk://mesos02:2181,mesos01:2181,mesos03:2181/mesos --total-executor-cores 16
```

And use Ctl-D to close the session so the spark framework gets cleaned up properly in Mesos.

**Comment by mjcollin** [comment]
Today's update: Still no real progress w/ either the ir kernel.json path (JVM does not start) or the manual connect path (can't limit CPU resources). However, can do the manual connection and start Spark locally on the JupyterHub server which avoids eating all the resources on the Mesos cluster. Only one person at a time can do this of course. Open a new R notebook (not SparkR) and add this to a cell:

```
Sys.setenv(HADOOP_CONF_DIR="/etc/hadoop/conf")
Sys.setenv(HADOOP_USER_NAME="hdfs")
Sys.setenv(SPARK_HOME="/opt/spark/latest")
library(SparkR, lib.loc = c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib")))
sc <- sparkR.session(master = "local[*]")
```

Then test with:

```
df <- read.df("/guoda/data/idigbio-20161119-100k.parquet") 
dim(df)
```

**Comment by saniyasahdev** [comment]
Yes the commands run perfectly fine on the R notebook. Let's see if I can
construct a dataframe containing other fields.
Thank you!

On Fri, Jun 2, 2017 at 11:23 AM, Matthew J Collins <notifications@github.com

**Comment by jhpoelen** [comment]
Looks like the issue has been resolved. Please comment / re-open if this is not the case.
