### ISSUE TITLE
jenkins updateAll job is not correctly updating the status of the job.

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#70]
per @jhpoelen :

I suspect that the program "curl" in the monitor bash script stalled. Suggest to include a timeout to avoid the script from stalling. https://unix.stackexchange.com/questions/94604/does-curl-have-a-timeout/94612 . You can add the timeout parameter by updating the bash script in https://github.com/gimmefreshdata/archive-importer/blob/master/archives.groovy#L90 .

**Comment by jhpoelen** [comment]
@jhammock I'd be happy to review any changes made to fix this. Also, please feel free to cancel the updateAll job in jenkins, as it has been stalled for a while.

**Comment by jhammock** [comment]
oh, I couldn't figure out how to cancel Jenkins jobs. Is it the little x beside the job record in the Build History?

**Comment by jhpoelen** [comment]
Sounds about right. Here's how I would find out: http://lmgtfy.com/?q=how+to+cancel+jenkins+jobs .

**Comment by jhpoelen** [comment]
But seriously, do holler if search engines do not offer suitable answers.

**Comment by jhammock** [comment]
:) Your prompt sent me down memory lane. I think I've been here before: Google does suggest a couple of sources that seem to favor the little red x, but selecting it a couple of times has produced no visible effect...

**Comment by jhpoelen** [comment]
hmm. Did you abort via http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/127/ ?

**Comment by jhammock** [comment]
that's the one, March 26

**Comment by jhpoelen** [comment]
It does seem to be unresponsive. How about this - I can try to clean out the build, if you apply the fix suggested earlier.

**Comment by jhpoelen** [comment]
The job stopped after I clicked all the abort / kill and cancel buttons.

From tail of http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/127/console :

```
Aborted by jhammock
Click here to forcibly terminate running steps
Aborted by Jorrit Poelen
Click here to forcibly terminate running steps
Terminating node
Click here to forcibly kill entire build
Hard kill!
Finished: ABORTED
```

**Comment by jhpoelen** [comment]
@jhammock suggest to close issue after http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/128/ .

**Comment by jhammock** [comment]
ah, missed this one...
