### ISSUE TITLE
remove marathon from guoda infrastructure

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#78]
Marathon is no longer used (see #73) , but is still installed in guoda infrastructure. While marathon can be manually stopped, it appears to restart on system failover events in case of system stress (see #77) and taking up all the system resource. See attached screenshot
![Screenshot from 2019-09-18 17-42-03](https://user-images.githubusercontent.com/1084872/65200645-7ce84300-da3c-11e9-9873-7e5dd7be9b94.png)
). 

@mielliott @roncanepa - please let me know how I can provide information on how to remove the marathon instance from the guoda infrastructure .

**Comment by roncanepa** [comment]
I've stopped and disabled marathon on the 3 master nodes.

**Comment by jhpoelen** [comment]
@roncanepa Thanks for making this happen. Closing issue.
