### ISSUE TITLE
hdfs and spark job performance

### ISSUE THREAD

**Issue by roncanepa** [bio-guoda/guoda-services#79]
New ticket for tracking performance issues reported by users.

Some initial background info:

hdfs is not designed for many small files.  The default block size is usually 64MB.  This will impact performance for loading into and reading from hdfs.

The machines in question are getting ~1GB/s between them.  As far as I'm aware, 10GB is not available, but am still researching the possibility.

```
root@preston:~# iperf3 -c 10.13.44.18 -t 120 -i 15
Connecting to host 10.13.44.18, port 5201
[  4] local 10.244.17.40 port 37854 connected to 10.13.44.18 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-15.00  sec  1.56 GBytes   896 Mbits/sec  183    764 KBytes       
[  4]  15.00-30.00  sec  1.57 GBytes   900 Mbits/sec  121    880 KBytes       
[  4]  30.00-45.00  sec  1.56 GBytes   893 Mbits/sec   65    905 KBytes       
[  4]  45.00-60.00  sec  1.56 GBytes   895 Mbits/sec   39    901 KBytes       
[  4]  60.00-75.00  sec  1.57 GBytes   899 Mbits/sec  157    706 KBytes       
[  4]  75.00-90.00  sec  1.57 GBytes   899 Mbits/sec  100    557 KBytes       
[  4]  90.00-105.00 sec  1.59 GBytes   908 Mbits/sec   32   1.06 MBytes       
[  4] 105.00-120.00 sec  1.57 GBytes   898 Mbits/sec  140    996 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-120.00 sec  12.5 GBytes   898 Mbits/sec  837             sender
[  4]   0.00-120.00 sec  12.5 GBytes   898 Mbits/sec                  receiver
```

drives:
```
# lsblk -o NAME,PHY-SEC
NAME   PHY-SEC
sda        512
├─sda1     512
├─sda2     512
└─sda5     512

root@mesos01:~# dd if=/dev/zero of=test1.img bs=512 count=100000
100000+0 records in
100000+0 records out
51200000 bytes (51 MB, 49 MiB) copied, 0.534646 s, 95.8 MB/s

root@mesos01:~# dd if=/dev/zero of=test1.img bs=512 count=10000000
10000000+0 records in
10000000+0 records out
5120000000 bytes (5.1 GB, 4.8 GiB) copied, 49.4393 s, 104 MB/s
```

Nodes 01-02 are namenodes.  1-3 are also the hdfs journal nodes.  From  /etc/hadoop/conf-2.7.1/hdfs-site.xml:
```
qjournal://mesos02.acis.ufl.edu:8485;mesos01.acis.ufl.edu:8485;mesos03.acis.ufl.edu:8485/hdfscluster
```

Disk contention could be a factor with having to seek + write both to the journal and the data on the same disks.  As mentioned before, hdfs is not meant for lots of small files.  If the namenodes are struggling in this regard, we could implement secondary namenodes.  These are different from standby namenodes:

- standby namenodes are an HA config meant to take over as primary if zk forces an election
- secondary namenodes help compact the various journals and logs to help the primary namemode stay caught up

Another option would be to try to compact incremental data files outside of hdfs and then ship them to hdfs and build up the bigger parquet files inside of hdfs + spark.

**Comment by jhpoelen** [comment]
@roncanepa I found your details are very insightful: disk access looks like the bottleneck. Also, from #77 , I've learned that one of the bottlenecks / blockers is related to storage space. See also @ialzuru sizing estimate document at https://github.com/bio-linker/change_tracker/blob/master/SpaceRequirements.pdf . would you like me to open a separate issue for storage volume needs?

**Comment by roncanepa** [comment]
Data and job design also come into play.  Any aggregation of files you can do before adding to hdfs will help with both the transfer and job completion time.  The default block size for hdfs is usually 64MB.  My understanding is that for any file, even if it's 1MB, will require at minimum one task to be spun up to read it, and the more files (and thus blocks) there are, the more the namenodes have to keep track of.  So you can see a significant improvement in job completion times if you can bundle some things up first.

**Comment by jhpoelen** [comment]
@roncanepa I acknowledge the small file problem and agree that data and job design (e.g., aggregating files) helps. For instance, we introduced sequence files some time ago to aggregate a large collection of small meta.xml and eml.xml files. These sequence files greatly reduced processing time.

 A naive thought: it possible to move the 1. and 2. files to a zfs filesystem that is accessible to compute as a network share? This would off-load the many small files, but still keep them available to the compute cluster.

**Comment by roncanepa** [comment]
That should already be doable.  All the data on preston.acis.ufl.edu lives on an nfs share, so  @mielliott or @ialzuru can mount that share read-only (for starters, probably best to not try to directly output to there) to all the mesos hosts.
