### ISSUE TITLE
connect linker.bio to deeplinker.bio

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#83]
we own linker.bio and deeplinker.bio . For historic reasons, we are using deeplinker.bio. However, linker.bio is shorter. Suggest to apply the DNS settings of deeplinker.bio to linker.bio . Alternatively, the ACIS folks in Florida can setup their preston mirror and serve the mirrored content via https://linker.bio/ .

If all is complete, 

https://deeplinker.bio/9a41d2583f0b8169ffdd44fb2d3a5e057eba4a10e5d9193d0c6e9dcf07c3119e

and 

https://linker.bio/9a41d2583f0b8169ffdd44fb2d3a5e057eba4a10e5d9193d0c6e9dcf07c3119e

should serve the same content.

@roncanepa @mielliott please confirm that you have access to DNS settings for linker.bio .

**Comment by roncanepa** [comment]
We do have access to linker.bio.  Would you like us to point it at 176.9.112.22 (which is what deeplinker is pointing to)? We won't be able to get around to the mirror immediately.

**Comment by jhpoelen** [comment]
@roncanepa thanks for the quick reply! Pointing to 176.9.112.22 would be great start . . . let me know if you need more info.

**Comment by roncanepa** [comment]
I haven't forgotten about this.  We took the opportunity to do some housekeeping on our side.  I should be able to make the DNS change next week.

**Comment by jhpoelen** [comment]
Thanks for your update!

**Comment by jhpoelen** [comment]
@roncanepa I just pinged linker.bio and found:

```
$ ping linker.bio
PING linker.bio (185.199.108.153) 56(84) bytes of data.
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=1 ttl=58 time=41.8 ms
64 bytes from 185.199.108.153 (185.199.108.153): icmp_seq=2 ttl=58 time=31.0 ms
```

**Comment by jhpoelen** [comment]
However when pinging deeplinker.bio :

```
$ ping deeplinker.bio
PING deeplinker.bio (176.9.112.22) 56(84) bytes of data.
64 bytes from preston (176.9.112.22): icmp_seq=1 ttl=51 time=210 ms
64 bytes from preston (176.9.112.22): icmp_seq=2 ttl=51 time=184 ms
```
