### ISSUE TITLE
Resources status page

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#9]
From @jhpoelen 

unfortunately, when I was trying to run my https://gist.github.com/jhpoelen/18b5ffe083f32dd1dca360a83e34cfd3 ... not enough resources were available. Would be nice to have some public page answering the questions : how busy is the server and who's using it.

**Comment by mjcollin** [comment]
Zabbix graphs but method to post on public site?

**Comment by jhpoelen** [comment]
The mesos monitor pages also have useful stats / info. Perhaps a job server / or queuing mechanism might help - then the "there are four jobs ahead of you" might give some indication of how busy the system is. A console / shell session would be considered a long-running job. 

Looking forward to discussing this tomorrow.

**Comment by jhpoelen** [comment]
related to/duplicate of #19 .
